spring:
  application:
    name: haruapp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # 실제 OpenAI 키로 대체
      chat:
        options:
          model: gpt-4.1-nano  # 또는 gpt-4.1-nano 등

  data:
    redis:
      url: ${REDIS_URL}

  mail:
    host: smtp.gmail.com
    port: 587
    username: mapharu00@gmail.com
    password: lqnvfhlfivovivmv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: org.example.haruapp
  configuration:
    map-underscore-to-camel-case: true

weather:
  key: ${WEATHER-API-KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    
toss:
  mid: ${TOSS_MID}
  secret-key: ${TOSS_SECRET_KEY}

