spring:
  application:
    name: haruapp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}  # 실제 OpenAI 키로 대체
      options:
        model: gpt-4.1-nano

  data:
    redis:
      url: ${REDIS_URL}
mybatis:
  type-aliases-package: org.example.haruapp
  configuration:
    map-underscore-to-camel-case: true

weather:
  key: ${WEATHER-API-KEY}