spring:
  application:
    name: haruapp
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: org.example.haruapp
  configuration:
    map-underscore-to-camel-case: true

weather:
  key: ${WEATHER-API-KEY}

gemini:
  api:
    key: ${GEMINI_API_KEY}

openai:
  api:
    ket: ${OPENAI_API_KEY}